name: roguelike CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_linux:
    name: build linux
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: install_dependencies
      run: |
         sudo apt-get update -y -qq
         sudo apt-get install -y libsdl2-dev libsdl2-mixer-dev libsdl2-gfx-dev libsdl2-image-dev libsdl2-ttf-dev
    - name: Build
      run: make
